// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wisshvyxmgjcydgjkike.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpc3Nodnl4bWdqY3lkZ2praWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjcwMDAsImV4cCI6MjA2NTY0MzAwMH0.V5Y3U2TS65iDVOChlsIDX5CLPpQ2onwLMVKUsV5UzP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);